title: Geek Guidebook
author: isaiaspereira307
email: isaias.pereira@protonmail.com
description: >
  This site talk about tecnology.
show_excerpts: true

sass:
  sass_dir: _sass
plainwhite:
  name: Isaías Pereira
  tagline: Developer.
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: true
  html_lang: "en"
  condensed_mobile:
    - home
    - page
    - post

  social_links:
    github:  isaiaspereira307
    linkedIn: in/isaías-dos-santos-33505714b
    email: isaias.pereira@protonmail.com


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: samarsault/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
